geoserver:
  # Set to the REST API for the GeoServer
  url: "http://localhost:8080/geoserver/rest"
  # Optional user/password, set to false to disable
  user: "admin"
  password: "admin123"
  # Set to your GWC server, or "builtin" for the one bundled with GeoServer
  geowebcache_url: "builtin"

  # RestClient: 
  restclient:
    # Set to false to disable or stdout/stderr or 'filename.out'
    logfile: 'rgeoserver.log' #stdout
    # Timeout (in seconds)
    timeout: 300
    # Open Timeout (in seconds)
    open_timeout: 60
